#preload = /home/zain/.config/hypr/racing-car-night-speed-desktop-wallpaper-preview.jpg
#if more than one preload is desired then continue to preload other backgrounds
#preload = /path/to/next_image.png
# .. more preloads
 
preload = /home/zain/.config/hypr/od_tux.png

wallpaper {
  monitor =
  path = /home/zain/.config/hypr/od_tux.png
}

#if more than one monitor in use, can load a 2nd image
#wallpaper = monitor2,/path/to/next_image.png
# .. more monitors
 
#enable splash text rendering over the wallpaper
splash = false
 
#fully disable ipc
# ipc = off
